### ISSUE TITLE
Backup and restore from backups

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry-incubator/cfcr-etcd-release#5]
Is there a standard way to take Backup of the ETCD data?

Is there a recommendation for the users of this release how one can implement B&R for this release?

Regards,
Subhankar

**Comment by tvs** [comment]
I'm not sure that we have a recommendation for etcd alone. I suppose your best bet would be to check the etcd docs site: https://coreos.com/etcd/docs/latest/v2/admin_guide.html#disaster-recovery

We've recently begun exploring disaster recovery in the context of Kubernetes (which, of course, includes etcd), but don't have anything ready to report.

**Comment by subhankarc** [comment]
Ok. Is there a place I can track for the disaster recovery of CFCR?

**Comment by tvs** [comment]
There's a label on tracker titled `disaster-recovery-exploration`. The first story that we've started on it is here: https://www.pivotaltracker.com/story/show/156502287
