### ISSUE TITLE
bbr backup?

### ISSUE THREAD

**Issue by lnguyen** [cloudfoundry-incubator/cfcr-etcd-release#6]
Is there any plans to add bbr support?

**Comment by iainsproat** [comment]
Hi @lnguyen , there's an ongoing exploration by the team to investigate disaster recovery.  You can follow the stories at: https://www.pivotaltracker.com/n/projects/2093412/search?q=label%3A%22disaster-recovery-exploration%22

**Comment by glestaris** [comment]
closing this since we will be soon working on it
