### ISSUE TITLE
Support metrics endpoint

### ISSUE THREAD

**Issue by making** [cloudfoundry-incubator/cfcr-etcd-release#8]
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/monitoring.md#metrics-endpoint
It would be great if metrics endpoint flag is enabled and etcd can be monitored by prometheus-bosh-release.

**Comment by alex-slynko** [comment]
Hi @making 

This idea definitely makes sense. Please send us the PR to allow us optionally enable this flag and we will merge it.

**Comment by making** [comment]
Sorry, I misunderstood. The endpoint has been already enabled
I was able to access `/metrics`
```
curl --cert /var/vcap/jobs/etcd/config/etcd.crt --key /var/vcap/jobs/etcd/config/etcd.key --cacert /var/vcap/jobs/etcd/config/etcd-ca.crt -k -v https://localhost:2379/metrics
```

**Comment by alex-slynko** [comment]
Hi @making

I would like to mention that etcd 3.3 allows operator to specify custom property to disable authentication from `/metrics` endpoint https://github.com/etcd-io/etcd/issues/8060

This property is not exposed yet. I thought you meant exposing it. We will accept PR for exposing this optionally, so the operator can choose the best thing for their environment.

**Comment by making** [comment]
Ok, I'll make a pr to expose `--listen-metrics-urls`.
Is there any policy to test the change?
